import sqlite3
import uuid
import datetime
import random

def seed():
    # Connect to the SQLite DB generated by Tauri
    conn = sqlite3.connect('apps/desktop/src-tauri/twoline.db')
    cursor = conn.cursor()

    quotes = [
        "The quieter you become, the more you are able to hear.",
        "Do what you can, with what you have, where you are.",
        "It always seems impossible until it's done.",
        "Success is not final, failure is not fatal.",
        "Happiness is not something ready made."
    ]

    # Start from 10 days ago
    curr = datetime.datetime.now() - datetime.timedelta(days=10)

    for i in range(50):
        d_str = curr.strftime('%Y-%m-%d')
        entry_id = str(uuid.uuid4())
        body = random.choice(quotes) + f" (Entry #{50 - i})"
        now = datetime.datetime.now().isoformat() + "Z"

        cursor.execute(
            """INSERT OR IGNORE INTO entries (id, date, body, created_at, updated_at, is_deleted) 
               VALUES (?, ?, ?, ?, ?, 0)""",
            (entry_id, d_str, body, now, now)
        )

        cursor.execute(
            "INSERT INTO entries_fts(rowid, body) VALUES (?, ?)",
            (entry_id, body)
        )

        # Skip a day to create gaps
        curr -= datetime.timedelta(days=2)

    conn.commit()
    conn.close()
    print("Successfully seeded 50 past entries into SQLite!")

if __name__ == "__main__":
    seed()
